name: IsekaiOrpheusBot
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: FrontEnd Angular CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Run Install Dependences
        run: npm i --legacy-peer-deps
  unit-test :
    needs: build
    - name: Run Unit Test Jasmine  
      run:  npm run unit-test
  e2e-testing : 
    needs: build
    - name : Cypress E2E Test
      run: npm run e2e:ci
  sonarcloud:
    needs : [build ,unit-test]
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
